# Generated by Django 5.0.6 on 2024-06-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_product_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_currency',
            new_name='sale_price_currency',
        ),
    ]
