# Generated by Django 5.0.6 on 2024-06-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_sale_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
